### ISSUE TITLE
VAAL implementation is incomplete?

### ISSUE THREAD

**Issue by saifullah3396** [SineZHAN/deepALplus#1]
Hi is VAAL implementation incorrect in this toolkit. I see that it is very different from the author's original implementation and it also looks incomplete, unusable. Can you please let me know if it is?

**Comment by gokyeongryeol** [comment]
I agree with your point. In current version, the parameter of VAE is not being updated.

**Comment by SineZHAN** [comment]
> Hi is VAAL implementation incorrect in this toolkit. I see that it is very different from the author's original implementation and it also looks incomplete, unusable. Can you please let me know if it is?

In https://github.com/SineZHAN/deepALplus/blob/master/query_strategies/vaal.py
vaal-vae is trained in line 31.

**Comment by SineZHAN** [comment]
> Hi is VAAL implementation incorrect in this toolkit. I see that it is very different from the author's original implementation and it also looks incomplete, unusable. Can you please let me know if it is?

Thank you for point out this issue, I found that I wrongly merged the vaal version (the old version lost discriminator part). I have updated it.
