### ISSUE TITLE
Custom Dataset

### ISSUE THREAD

**Issue by ghost** [SineZHAN/deepALplus#3]
Hello,

Is there any way to test this code with a custom image dataset?

Thank you

**Comment by SineZHAN** [comment]
> 

Hi, you can 1) write a new function get_yourowndata() into data.py,  multiple examples are included in data.py; then 2) write a new handler or use the existing handler like CIFAR10 handler into handler.py; 3) write a new network in nets.py or use existing network like ResNet18; finally add code in utils.py to specify the nets, data pre-processing and handlers our your custom image dataset in functions get_net(), get_dataset() and get_handler() respectively.

**Comment by ghost** [comment]
Thank you
